### ISSUE TITLE
ValueError: x and y must have length at least 2.

### ISSUE THREAD

**Issue by chun-he-316** [JLSteenwyk/PhyKIT#28]
Hello,
I want to use phykit to evaluate gene-gene covariation, the command looks like this: "phykit cover treefiles/gene1.treefile.rooted treefiles/gene2.treefile.rooted -r tree.rooted.txt". However, I met this error: "ValueError: x and y must have length at least 2". Please tell me how to resolve this problem. Thanks.
The best,
Chun

**Comment by JLSteenwyk** [comment]
Hi Chun,

Thank you so much for writing and for using PhyKIT!

Would you please share your input files for me to better diagnose the issue?

Feel free to send them here or email me directly [https://jlsteenwyk.com/contact.html](https://jlsteenwyk.com/contact.html).

best,

Jacob

**Comment by chun-he-316** [comment]
Hi Jacob，


Thank you so much for answering me. I really need your help.
The three attachments are our input files. tree.rooted.txt is the species tree. OG0000038.treefile and OG0000041.treefile are two gene trees, and the branch length is the inferred corresponding gene count. So I use the command "phykit cover OG0000038.treefile OG0000041.treefile -r tree.rooted.txt".
The error is "ValueError: x and y must have length at least 2". Please tell me how to resolve this problem. Thanks.


In addition, I tried the examples in "https://jlsteenwyk.com/PhyKIT/tutorials/index.html#evaluating-gene-gene-covariation", but the result was nothing like the tutorials. I do not know why. The results are as follows:
"phykit cover Shen_etal_SciAdv_2020_NDC80.treefile.rooted Shen_etal_SciAdv_2020_SEC7.treefile.rooted -r Shen_etal_SciAdv_2020_species_tree.tre
0.2105 0.0
phykit cover Shen_etal_SciAdv_2020_NUF2.treefile.rooted Shen_etal_SciAdv_2020_SEC7.treefile.rooted -r Shen_etal_SciAdv_2020_species_tree.tre
0.1885 0.0"

The best,

Chun



| |
何纯
|
|
***@***.***
|
---- Replied Message ----
| From | Jacob L. ***@***.***> |
| Date | 3/4/2024 23:32 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [JLSteenwyk/PhyKIT] ValueError: x and y must have length at least 2. (Issue #28) |

Hi Chun,

Thank you so much for writing and for using PhyKIT!

Would you please share your input files for me to better diagnose the issue?

Feel free to send them here or email me directly https://jlsteenwyk.com/contact.html.

best,

Jacob

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>
(Athalia_rosae:0.05245982185,(((Rhogogaster_chlorosoma:0.0254586934,(Tenthredo_mesomela:0.0197303692,Tenthredo_notha:0.0183362910):0.0142943587[100]):0.0601533422[100],(Diprion_similis:0.0211248043,(Neodiprion_lecontei:0.0027214541,(Neodiprion_virginianus:0.0015736348,Neodiprion_fabricii:0.0015976110):0.0007619162[100]):0.0230274575[100]):0.0869959139[100]):0.0177155585[100],(Cephus_cinctus:0.1625944139,(Orussus_abietinus:0.2410305276,((((Belonocnema_kinseyi:0.1154912158,(Leptopilina_heterotoma:0.0516817665,Leptopilina_boulardi:0.0460090001):0.1201519788[100]):0.1485519186[100],(Telenomus_remus:0.4351201326,(((Copidosoma_floridanum:0.2390898341,Eretmocerus_hayati:0.2553214405):0.0255336609[95],(Chouioia_cunea:0.1845675032,Trichogramma_pretiosum:0.3687046239):0.0242238919[95]):0.0099183400[95],((Theocolax_elegans:0.1335126251,(Ceratosolen_solmsi:0.1107686589,Eupristina_verticillata:0.1190300282):0.0721664717[100]):0.0130634397[100],((Anastatus_fulloi:0.0052175581,Anastatus_japonicus:0.0042486970):0.1173923665[100],(Pachycrepodieus_vindemmiae:0.0699166512,(Anisopteromalus_calandrae:0.0386632813,((Nasonia_vitripennis:0.0062073119,Trichomalopsis_sarcophagae:0.0112688240):0.0140000162[100],(Pteromalus_qinghaiensis:0.0052584002,(Pteromalus_venustus:0.0049853363,Pteromalus_puparum:0.0044792464):0.0025708941[100]):0.0149073333[100]):0.0255526393[100]):0.0241841937[100]):0.0558191971[100]):0.0099901456[99]):0.0133857216[100]):0.1974470288[100]):0.0293246678[100]):0.0425047852[100],(((Ophion_luteus:0.1122778938,Venturia_canescens:0.0988949610):0.0695243592[100],(Buathra_laborator:0.0646358213,(Diadromus_collaris:0.0426406613,(Ichneumon_xanthorius:0.0172826675,Amblyteles_armatorius:0.0146136250):0.0200841785[100]):0.0360616416[100]):0.0527527849[100]):0.0997455076[100],(((Aphidius_gifuensis:0.1767998036,Binodoxys_communis:0.1322287141):0.1652318922[100],(Habrobracon_hebetor:0.1843370690,(Diachasma_alloeum:0.0527464275,Fopius_arisanus:0.0763537627):0.0745990771[100]):0.0851009870[100]):0.0344215062[100],((Macrocentrus_cingulum:0.2483520687,(Microctonus_aethiopoides:0.0184552660,Microctonus_hyperodae:0.0242902887):0.1580427127[100]):0.0210238915[100],(Chelonus_insularis:0.1885800151,((Microplitis_demolitor:0.0118800725,Microplitis_mediator:0.0114548346):0.0481401750[100],(Apanteles_cypris:0.0414257218,(Cotesia_glomerata:0.0156429202,(Cotesia_chilonis:0.0143760487,Cotesia_sesamiae:0.0085908649):0.0129744580[100]):0.0341571425[100]):0.0478347422[100]):0.1415490813[100]):0.0480506876[100]):0.0429146220[100]):0.0878072319[100]):0.0678690359[100]):0.0143602440[100],(Gonatopus_flavifemur:0.2517423464,((Ancistrocerus_nigricornis:0.0697995410,((Mischocyttarus_mexicanus:0.0419371434,(Polistes_dominula:0.0278409606,(Polistes_canadensis:0.0099515518,Polistes_fuscatus:0.0092995261):0.0072979809[100]):0.0106863155[100]):0.0458911475[100],((Vespula_germanica:0.0069321749,(Vespula_vulgaris:0.0030478373,Vespula_pensylvanica:0.0034488722):0.0008591188[100]):0.0159766724[100],((Dolichovespula_media:0.0119801346,(Dolichovespula_sylvestris:0.0094336081,Dolichovespula_saxonica:0.0144452922):0.0039988607[100]):0.0177257630[100],(Vespa_velutina:0.0041684055,(Vespa_mandarinia:0.0039198367,Vespa_crabro:0.0032220272):0.0006312989[99]):0.0159108268[100]):0.0062806302[100]):0.0181812950[100]):0.0371200496[100]):0.1275896793[100],((Anoplius_nigerrimus:0.1733085280,Tiphia_femorata:0.1702649048):0.0269813567[100],(((Dinoponera_quadriceps:0.0531360417,(Harpegnathos_saltator:0.0509804246,Odontomachus_brunneus:0.0484397990):0.0065886039[100]):0.0620575577[100],((Eciton_burchellii:0.0694444332,Ooceraea_biroi:0.0498713652):0.0500802405[100],((Linepithema_humile:0.0768551055,Pseudomyrmex_gracilis:0.1248902633):0.0098269160[100],((Nylanderia_fulva:0.0506616185,(Camponotus_floridanus:0.0397589782,(Formica_exsecta:0.0170745408,Cataglyphis_hispanica:0.0240367401):0.0155740272[100]):0.0098646955[100]):0.0375652602[100],(Pogonomyrmex_barbatus:0.0605779228,((Vollenhovia_emeryi:0.0531372177,(Temnothorax_longispinosus:0.0092068091,Temnothorax_curvispinosus:0.0028782638):0.0327655651[100]):0.0099152051[100],((Solenopsis_invicta:0.0385937620,Monomorium_pharaonis:0.0471308944):0.0170222612[100],(Wasmannia_auropunctata:0.0452053303,(Cyphomyrmex_costatus:0.0330029473,(Trachymyrmex_zeteki:0.0181139945,(Trachymyrmex_cornetzi:0.0126367721,(Trachymyrmex_septentrionalis:0.0139088670,(Atta_colombica:0.0141218783,((Acromyrmex_echinatior:0.0023427127,Acromyrmex_insinuator:0.0037000143):0.0050658467[100],(Pseudoatta_argentina:0.0072437060,Acromyrmex_charruanus:0.0030678299):0.0051381236[100]):0.0068240170[100]):0.0020237804[100]):0.0019935862[100]):0.0069298900[100]):0.0076331208[100]):0.0274820704[100]):0.0065535296[100]):0.0026737821[100]):0.0139627326[100]):0.0280531770[100]):0.0074921463[100]):0.0078708567[100]):0.0257583977[100]):0.1059882684[100],(Ampulex_compressa:0.1595536261,((Nysson_spinosus:0.1332364711,Ectemnius_continuus:0.2009551155):0.0139406615[100],((Pemphredon_lugubris:0.1142632571,Cerceris_rybyensis:0.1209593557):0.0108746455[97],(Mimumesa_dahlbomi:0.1082003149,(Macropis_europaea:0.0931128180,(((Andrena_dorsata:0.0190214413,(Andrena_fulva:0.0214368329,Andrena_haemorrhoa:0.0177774870):0.0030319897[100]):0.0784534068[100],((Colletes_gigas:0.0621244234,(Hylaeus_volcanicus:0.0024129868,Hylaeus_anthracinus:0.0022061792):0.0574785440[100]):0.0279660704[100],(Dufourea_novaeangliae:0.0685219753,(Nomia_melanderi:0.0611635498,(Megalopta_genalis:0.0521992351,(Sphecodes_monilicornis:0.0316818260,(Lasioglossum_morio:0.0326485232,Seladonia_tumulorum:0.0260957593):0.0075582870[100]):0.0229375034[100]):0.0300942148[100]):0.0236132786[100]):0.0288850843[100]):0.0090598466[100]):0.0097885001[100],(((Anthidium_xuezhongi:0.0343484667,Stelis_phaeoptera:0.0358295352):0.0196348424[100],(Megachile_rotundata:0.0504827072,(Osmia_bicornis:0.0064756727,Osmia_lignaria:0.0050952634):0.0383064915[100]):0.0069140340[100]):0.0443140639[100],((Holcopasites_calliopsidis:0.0954796662,Habropoda_laboriosa:0.0692189839):0.0049226699[63],(Ceratina_calcarata:0.1203681425,(Eufriesea_mexicana:0.0624674709,((Apis_florea:0.0102476385,(Apis_mellifera:0.0085187718,Apis_cerana:0.0081859453):0.0056542401[100]):0.0530146489[100],((Melipona_quadrifasciata:0.0239503665,Frieseomelitta_varia:0.0117153783):0.0383218041[100],(Bombus_pyrosoma:0.0071251901,(Bombus_impatiens:0.0081489112,Bombus_terrestris:0.0088485666):0.0016906078[100]):0.0346571866[100]):0.0155574226[100]):0.0058130673[100]):0.0154759696[100]):0.0079722803[100]):0.0171077313[100]):0.0191022363[100]):0.0081024592[100]):0.0414079581[100]):0.0063794155[46]):0.0189635902[100]):0.0244321782[100]):0.0204390695[100]):0.0160566987[100]):0.0086377067[51]):0.0238406317[100]):0.0584434146[100]):0.0224852975[100]):0.0246036678[100]):0.1782366104[100]):0.05245982185);

**Comment by JLSteenwyk** [comment]
Hi Chun,

I got an email that you responded but do not see the response on GitHub. If this correct, please send your files via email.

All the best,

Jacob

**Comment by chun-he-316** [comment]
Hi Jacob，
Thank you so much for answering me.
I will send the input file to you by email. tree.rooted.txt is the species tree. gene1.treefile and gene2.treefile are two gene trees, and the branch length is the inferred corresponding gene count. So I use the command "phykit cover gene1.treefile gene2.treefile -r tree.rooted.txt". I have sent it to you by email, please check.
The error is "ValueError: x and y must have length at least 2". Please tell me how to resolve this problem. Thanks.
In addition, I tried the examples in "[https://jlsteenwyk.com/PhyKIT/tutorials/index.html#evaluating-gene-gene-covariation"](https://jlsteenwyk.com/PhyKIT/tutorials/index.html#evaluating-gene-gene-covariation%22.But), but the result was nothing like the tutorials. I do not know why. The results are as follows:
"phykit cover Shen_etal_SciAdv_2020_NDC80.treefile.rooted Shen_etal_SciAdv_2020_SEC7.treefile.rooted -r Shen_etal_SciAdv_2020_species_tree.tre
0.2105 0.0
phykit cover Shen_etal_SciAdv_2020_NUF2.treefile.rooted Shen_etal_SciAdv_2020_SEC7.treefile.rooted -r Shen_etal_SciAdv_2020_species_tree.tre
0.1885 0.0"
The best,
Chun


| |
何纯
|
|
***@***.***
|
---- Replied Message ----
| From | Jacob L. ***@***.***> |
| Date | 3/6/2024 04:19 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [JLSteenwyk/PhyKIT] ValueError: x and y must have length at least 2. (Issue #28) |

Hi Chun,

I got an email that you responded but do not see the response on GitHub. If this correct, please send your files via email.

All the best,

Jacob

**Comment by chun-he-316** [comment]
Hi Jacob，
Thank you so much for answering me.
I will send the input file to you by email. tree.rooted.txt is the species tree. gene1.treefile and gene2.treefile are two gene trees, and the branch length is the inferred corresponding gene count. So I use the command "phykit cover gene1.treefile gene2.treefile -r tree.rooted.txt". I have sent it to you by email, please check.
The error is "ValueError: x and y must have length at least 2". Please tell me how to resolve this problem. Thanks.
In addition, I tried the examples in "https://jlsteenwyk.com/PhyKIT/tutorials/index.html#evaluating-gene-gene-covariation", but the result was nothing like the tutorials. I do not know why. The results are as follows:
"phykit cover Shen_etal_SciAdv_2020_NDC80.treefile.rooted Shen_etal_SciAdv_2020_SEC7.treefile.rooted -r Shen_etal_SciAdv_2020_species_tree.tre
0.2105 0.0
phykit cover Shen_etal_SciAdv_2020_NUF2.treefile.rooted Shen_etal_SciAdv_2020_SEC7.treefile.rooted -r Shen_etal_SciAdv_2020_species_tree.tre
0.1885 0.0"
The best,
Chun


| |
何纯
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 3/6/2024 09:21 |
| To | ***@***.******@***.***> |
| Cc | ***@***.******@***.***> ,
***@***.******@***.***> |
| Subject | Re: [JLSteenwyk/PhyKIT] ValueError: x and y must have length at least 2. (Issue #28) |
Hi Jacob，
Thank you so much for answering me.
I will send the input file to you by email. tree.rooted.txt is the species tree. gene1.treefile and gene2.treefile are two gene trees, and the branch length is the inferred corresponding gene count. So I use the command "phykit cover gene1.treefile gene2.treefile -r tree.rooted.txt". I have sent it to you by email, please check.
The error is "ValueError: x and y must have length at least 2". Please tell me how to resolve this problem. Thanks.
In addition, I tried the examples in "[https://jlsteenwyk.com/PhyKIT/tutorials/index.html#evaluating-gene-gene-covariation"](https://jlsteenwyk.com/PhyKIT/tutorials/index.html#evaluating-gene-gene-covariation%22.But), but the result was nothing like the tutorials. I do not know why. The results are as follows:
"phykit cover Shen_etal_SciAdv_2020_NDC80.treefile.rooted Shen_etal_SciAdv_2020_SEC7.treefile.rooted -r Shen_etal_SciAdv_2020_species_tree.tre
0.2105 0.0
phykit cover Shen_etal_SciAdv_2020_NUF2.treefile.rooted Shen_etal_SciAdv_2020_SEC7.treefile.rooted -r Shen_etal_SciAdv_2020_species_tree.tre
0.1885 0.0"
The best,
Chun


| |
何纯
|
|
***@***.***
|
---- Replied Message ----
| From | Jacob L. ***@***.***> |
| Date | 3/6/2024 04:19 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [JLSteenwyk/PhyKIT] ValueError: x and y must have length at least 2. (Issue #28) |

Hi Chun,

I got an email that you responded but do not see the response on GitHub. If this correct, please send your files via email.

All the best,

Jacob

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>
(Athalia_rosae:0.05245982185,(((Rhogogaster_chlorosoma:0.0254586934,(Tenthredo_mesomela:0.0197303692,Tenthredo_notha:0.0183362910):0.0142943587[100]):0.0601533422[100],(Diprion_similis:0.0211248043,(Neodiprion_lecontei:0.0027214541,(Neodiprion_virginianus:0.0015736348,Neodiprion_fabricii:0.0015976110):0.0007619162[100]):0.0230274575[100]):0.0869959139[100]):0.0177155585[100],(Cephus_cinctus:0.1625944139,(Orussus_abietinus:0.2410305276,((((Belonocnema_kinseyi:0.1154912158,(Leptopilina_heterotoma:0.0516817665,Leptopilina_boulardi:0.0460090001):0.1201519788[100]):0.1485519186[100],(Telenomus_remus:0.4351201326,(((Copidosoma_floridanum:0.2390898341,Eretmocerus_hayati:0.2553214405):0.0255336609[95],(Chouioia_cunea:0.1845675032,Trichogramma_pretiosum:0.3687046239):0.0242238919[95]):0.0099183400[95],((Theocolax_elegans:0.1335126251,(Ceratosolen_solmsi:0.1107686589,Eupristina_verticillata:0.1190300282):0.0721664717[100]):0.0130634397[100],((Anastatus_fulloi:0.0052175581,Anastatus_japonicus:0.0042486970):0.1173923665[100],(Pachycrepodieus_vindemmiae:0.0699166512,(Anisopteromalus_calandrae:0.0386632813,((Nasonia_vitripennis:0.0062073119,Trichomalopsis_sarcophagae:0.0112688240):0.0140000162[100],(Pteromalus_qinghaiensis:0.0052584002,(Pteromalus_venustus:0.0049853363,Pteromalus_puparum:0.0044792464):0.0025708941[100]):0.0149073333[100]):0.0255526393[100]):0.0241841937[100]):0.0558191971[100]):0.0099901456[99]):0.0133857216[100]):0.1974470288[100]):0.0293246678[100]):0.0425047852[100],(((Ophion_luteus:0.1122778938,Venturia_canescens:0.0988949610):0.0695243592[100],(Buathra_laborator:0.0646358213,(Diadromus_collaris:0.0426406613,(Ichneumon_xanthorius:0.0172826675,Amblyteles_armatorius:0.0146136250):0.0200841785[100]):0.0360616416[100]):0.0527527849[100]):0.0997455076[100],(((Aphidius_gifuensis:0.1767998036,Binodoxys_communis:0.1322287141):0.1652318922[100],(Habrobracon_hebetor:0.1843370690,(Diachasma_alloeum:0.0527464275,Fopius_arisanus:0.0763537627):0.0745990771[100]):0.0851009870[100]):0.0344215062[100],((Macrocentrus_cingulum:0.2483520687,(Microctonus_aethiopoides:0.0184552660,Microctonus_hyperodae:0.0242902887):0.1580427127[100]):0.0210238915[100],(Chelonus_insularis:0.1885800151,((Microplitis_demolitor:0.0118800725,Microplitis_mediator:0.0114548346):0.0481401750[100],(Apanteles_cypris:0.0414257218,(Cotesia_glomerata:0.0156429202,(Cotesia_chilonis:0.0143760487,Cotesia_sesamiae:0.0085908649):0.0129744580[100]):0.0341571425[100]):0.0478347422[100]):0.1415490813[100]):0.0480506876[100]):0.0429146220[100]):0.0878072319[100]):0.0678690359[100]):0.0143602440[100],(Gonatopus_flavifemur:0.2517423464,((Ancistrocerus_nigricornis:0.0697995410,((Mischocyttarus_mexicanus:0.0419371434,(Polistes_dominula:0.0278409606,(Polistes_canadensis:0.0099515518,Polistes_fuscatus:0.0092995261):0.0072979809[100]):0.0106863155[100]):0.0458911475[100],((Vespula_germanica:0.0069321749,(Vespula_vulgaris:0.0030478373,Vespula_pensylvanica:0.0034488722):0.0008591188[100]):0.0159766724[100],((Dolichovespula_media:0.0119801346,(Dolichovespula_sylvestris:0.0094336081,Dolichovespula_saxonica:0.0144452922):0.0039988607[100]):0.0177257630[100],(Vespa_velutina:0.0041684055,(Vespa_mandarinia:0.0039198367,Vespa_crabro:0.0032220272):0.0006312989[99]):0.0159108268[100]):0.0062806302[100]):0.0181812950[100]):0.0371200496[100]):0.1275896793[100],((Anoplius_nigerrimus:0.1733085280,Tiphia_femorata:0.1702649048):0.0269813567[100],(((Dinoponera_quadriceps:0.0531360417,(Harpegnathos_saltator:0.0509804246,Odontomachus_brunneus:0.0484397990):0.0065886039[100]):0.0620575577[100],((Eciton_burchellii:0.0694444332,Ooceraea_biroi:0.0498713652):0.0500802405[100],((Linepithema_humile:0.0768551055,Pseudomyrmex_gracilis:0.1248902633):0.0098269160[100],((Nylanderia_fulva:0.0506616185,(Camponotus_floridanus:0.0397589782,(Formica_exsecta:0.0170745408,Cataglyphis_hispanica:0.0240367401):0.0155740272[100]):0.0098646955[100]):0.0375652602[100],(Pogonomyrmex_barbatus:0.0605779228,((Vollenhovia_emeryi:0.0531372177,(Temnothorax_longispinosus:0.0092068091,Temnothorax_curvispinosus:0.0028782638):0.0327655651[100]):0.0099152051[100],((Solenopsis_invicta:0.0385937620,Monomorium_pharaonis:0.0471308944):0.0170222612[100],(Wasmannia_auropunctata:0.0452053303,(Cyphomyrmex_costatus:0.0330029473,(Trachymyrmex_zeteki:0.0181139945,(Trachymyrmex_cornetzi:0.0126367721,(Trachymyrmex_septentrionalis:0.0139088670,(Atta_colombica:0.0141218783,((Acromyrmex_echinatior:0.0023427127,Acromyrmex_insinuator:0.0037000143):0.0050658467[100],(Pseudoatta_argentina:0.0072437060,Acromyrmex_charruanus:0.0030678299):0.0051381236[100]):0.0068240170[100]):0.0020237804[100]):0.0019935862[100]):0.0069298900[100]):0.0076331208[100]):0.0274820704[100]):0.0065535296[100]):0.0026737821[100]):0.0139627326[100]):0.0280531770[100]):0.0074921463[100]):0.0078708567[100]):0.0257583977[100]):0.1059882684[100],(Ampulex_compressa:0.1595536261,((Nysson_spinosus:0.1332364711,Ectemnius_continuus:0.2009551155):0.0139406615[100],((Pemphredon_lugubris:0.1142632571,Cerceris_rybyensis:0.1209593557):0.0108746455[97],(Mimumesa_dahlbomi:0.1082003149,(Macropis_europaea:0.0931128180,(((Andrena_dorsata:0.0190214413,(Andrena_fulva:0.0214368329,Andrena_haemorrhoa:0.0177774870):0.0030319897[100]):0.0784534068[100],((Colletes_gigas:0.0621244234,(Hylaeus_volcanicus:0.0024129868,Hylaeus_anthracinus:0.0022061792):0.0574785440[100]):0.0279660704[100],(Dufourea_novaeangliae:0.0685219753,(Nomia_melanderi:0.0611635498,(Megalopta_genalis:0.0521992351,(Sphecodes_monilicornis:0.0316818260,(Lasioglossum_morio:0.0326485232,Seladonia_tumulorum:0.0260957593):0.0075582870[100]):0.0229375034[100]):0.0300942148[100]):0.0236132786[100]):0.0288850843[100]):0.0090598466[100]):0.0097885001[100],(((Anthidium_xuezhongi:0.0343484667,Stelis_phaeoptera:0.0358295352):0.0196348424[100],(Megachile_rotundata:0.0504827072,(Osmia_bicornis:0.0064756727,Osmia_lignaria:0.0050952634):0.0383064915[100]):0.0069140340[100]):0.0443140639[100],((Holcopasites_calliopsidis:0.0954796662,Habropoda_laboriosa:0.0692189839):0.0049226699[63],(Ceratina_calcarata:0.1203681425,(Eufriesea_mexicana:0.0624674709,((Apis_florea:0.0102476385,(Apis_mellifera:0.0085187718,Apis_cerana:0.0081859453):0.0056542401[100]):0.0530146489[100],((Melipona_quadrifasciata:0.0239503665,Frieseomelitta_varia:0.0117153783):0.0383218041[100],(Bombus_pyrosoma:0.0071251901,(Bombus_impatiens:0.0081489112,Bombus_terrestris:0.0088485666):0.0016906078[100]):0.0346571866[100]):0.0155574226[100]):0.0058130673[100]):0.0154759696[100]):0.0079722803[100]):0.0171077313[100]):0.0191022363[100]):0.0081024592[100]):0.0414079581[100]):0.0063794155[46]):0.0189635902[100]):0.0244321782[100]):0.0204390695[100]):0.0160566987[100]):0.0086377067[51]):0.0238406317[100]):0.0584434146[100]):0.0224852975[100]):0.0246036678[100]):0.1782366104[100]):0.05245982185);

**Comment by chun-he-316** [comment]
Hi Jacob，

Thank you so much for answering me.
I will send the input file to you by email. tree.rooted.txt is the species tree. gene1.treefile and gene2.treefile are two gene trees, and the branch length is the inferred corresponding gene count. So I use the command "phykit cover gene1.treefile gene2.treefile -r tree.rooted.txt". I have sent it to you by email, please check.
The error is "ValueError: x and y must have length at least 2". Please tell me how to resolve this problem. Thanks.
In addition, I tried the examples in "[https://jlsteenwyk.com/PhyKIT/tutorials/index.html#evaluating-gene-gene-covariation"](https://jlsteenwyk.com/PhyKIT/tutorials/index.html#evaluating-gene-gene-covariation%22.But), but the result was nothing like the tutorials. I do not know why. The results are as follows:
"phykit cover Shen_etal_SciAdv_2020_NDC80.treefile.rooted Shen_etal_SciAdv_2020_SEC7.treefile.rooted -r Shen_etal_SciAdv_2020_species_tree.tre
0.2105 0.0
phykit cover Shen_etal_SciAdv_2020_NUF2.treefile.rooted Shen_etal_SciAdv_2020_SEC7.treefile.rooted -r Shen_etal_SciAdv_2020_species_tree.tre
0.1885 0.0"

The best,
Chun

**Comment by JLSteenwyk** [comment]
Hi Chun,

I haven't received an email yet and checked my spam box.

Please email me here: jlsteenwyk[at]berkeley[dot]edu

best,

Jacob

**Comment by chun-he-316** [comment]
Hi Jacob，

I have sent these files, please check.

The best,
Chun

**Comment by JLSteenwyk** [comment]
Hi Chun,

I'm sorry but I am still not receiving the emails. I'm sorry about the hassle.

Would you mind providing me your email address so I can send you a message?

best,

Jacob

**Comment by chun-he-316** [comment]
I sent it again. Did you get it? My email address is 18875076627@163.com. Thank you.

**Comment by chun-he-316** [comment]
I sent it again with Google Mail. Did it work this time? My E-mail address is chun31589@gmail.com

**Comment by chun-he-316** [comment]
In addition, I do not know what the two values in the output mean respectively. Can you explain it to me?

**Comment by JLSteenwyk** [comment]
Message received - thank you so much! I will work on diagnosing the issue now and get back to you 😄

**Comment by JLSteenwyk** [comment]
Hi Chen,

I have received the files - thank you for working with me on getting the files!

The reason you got this error is because the branch lengths in your input trees are _really_ long compared to the species tree. As described in [Steenwyk et al. (2022), _Science Advances_](https://www.science.org/doi/10.1126/sciadv.abn0105), outlier branch lengths get removed because they can cause spurious correlations. Outlier branches are defined as being 5 times the length of the species tree.

In your case, _all_ branches are outlier branches. Accordingly, all branches were getting removed.

To resolve this issue, I've added a new argument to the _cover_ function, the `-ot/--outlier_threshold` argument. This argument takes a float as input or a string "None" to specify that no threshold should be used.

Thus, for your example, you can execute the following command:
`pk_cover gene1.treefile gene2.treefile -r tree.rooted.txt -ot None`, which will produce the following output:
`0.8732  0.0`

As described in the help message of the _cover_ function (which you can view by executing `pk_cover -h`), these two values indicate the coevolutionary coefficient and the associated p-value. Here, the coevolutionary coefficient is 0.8732 and the p-value is 0.0.

The interpretation would be that there is strong evidence for coevolution because there is a high coevolutionary coefficient and a statistically significant signature of coevolution.

**This is now available in PhyKIT version 1.16.0**, which can be downloaded using `pip install phykit -U`; ([https://pypi.org/project/phykit/1.16.0/](https://pypi.org/project/phykit/1.16.0/)).

Lastly, regarding the error in the tutorial. Thank you for spotting that. I will address it shortly. The tutorial is currently incorrect and I will fix it soon. However, given that the tutorial is not pertinent to your use case, and I demonstrated the result with your example files, I will go ahead and close the comment. Please feel free to reopen the comment if you have an additional inquiry.

All the best,

Jacob

**Comment by chun-he-316** [comment]
Hi Jacob，

I already tried that, and it worked. Thank you very much.

The best,
Chun

**Comment by JLSteenwyk** [comment]
Dear Chun,

The tutorial has been fixed.

Thank you again for pointing out this error.

best,

Jacob
