### ISSUE TITLE
Phykit `thread_dna` with the log of Clipkit gives alignments of different lengths

### ISSUE THREAD

**Issue by MarionPerrier** [JLSteenwyk/PhyKIT#38]
Dear developers,

I am using Clipkit and Phykit to create a phylogenomics tree of 26 isolates of a species (+outgroup) on the single-copy unique orthologs.
Once I did the multi-alignments of my proteins and trimmed them using Clipkit, I would like to convert amino acids into DNA using `thread_dna`. However, the output shows alignments of different lengths.

I am using Phykit v1.19.8, installed through conda. Here is my command:

`phykit thread_dna -p 02_muscle/$SAMPLE*clipkit -c 02_muscle/$SAMPLE*.log -n 03_mrna_per_OG/$SAMPLE*fa > 04_pal2nal_mrna_log/$SAMPLE.pal2nal.afa`

Here are the input/output files on one OG (I renamed all the files with a ".txt" so they can be uploaded in github):

- trimmed protein alignment: [OG0002774.aln.afa.clipkit.txt](https://github.com/user-attachments/files/16346885/OG0002774.aln.afa.clipkit.txt)

- log clipkit: [OG0002774.aln.afa.clipkit.log.txt](https://github.com/user-attachments/files/16346887/OG0002774.aln.afa.clipkit.log.txt)

- transcripts: [OG0002774.mrna.fa.txt](https://github.com/user-attachments/files/16346891/OG0002774.mrna.fa.txt)

- output DNA: [OG0002774.pal2nal.afa.txt](https://github.com/user-attachments/files/16346889/OG0002774.pal2nal.afa.txt)

Is this a bug, or am I using Phykit wrongly? 

Thank you for your time and I wish you a nice day!
Marion

**Comment by JLSteenwyk** [comment]
Hi Marion,

Thank you for choosing to use PhyKIT and for writing with your issue. 

Would you mind also providing your untrimmed alignment to help diagnose the issue?

All the best,

Jacob

**Comment by MarionPerrier** [comment]
Hi Jacob,

Yes no problem! Thank you for your very quick answer.  
Here is the untrimmed alignment: 
[OG0002774.aln.afa.txt](https://github.com/user-attachments/files/16350287/OG0002774.aln.afa.txt)

Thank you for helping me out with this!

**Comment by MarionPerrier** [comment]
Hi Jacob,

Did you had the time to look at this issue? 

Regards,
Marion

**Comment by JLSteenwyk** [comment]
Hi Marion,

Sorry about the delayed response. 

Thank you for providing the input files.

Using PhyKIT 1.19.9, I executed the following command: `pk_thread_dna -p OG0002774.aln.afa.txt -c OG0002774.aln.afa.clipkit.log.txt -n OG0002774.mrna.fa.txt`, which resulted in all the sequences having the same alignment length of 1,209.

I also did the same thing with PhyKIT 1.19.8 and got the same result.

I'm not sure what the issue may be. 

Can you double-check things on your end? If the issue persists, I would happily set up a Zoom call to help resolve the issue.

best,

Jacob

**Comment by MarionPerrier** [comment]
Hi Jacob,

Thank you a lot for your answer.
I was using the software incorrectly: I put the trimmed protein alignment with the logfile as input instead of the untrimmed one. So, this issue was resolved for this specific OG.

However, the issue persists for other OGs other than the one I've previously uploaded. Here is a second example right under where one sample is shorter than the others after the thread_dna command:
`pk_thread_dna -p OG0000775.aln.afa.txt -c OG0000775.aln.afa.clipkit.log -n OG0000775.mrna.fa.txt > output.afa.txt`

The multialignment file has a length of 1812bp for all samples except for sample 25, which has a length of 1803.

[OG0000775.aln.afa.clipkit.log](https://github.com/user-attachments/files/16530461/OG0000775.aln.afa.clipkit.log)
[OG0000775.aln.afa.txt](https://github.com/user-attachments/files/16530462/OG0000775.aln.afa.txt)
[OG0000775.mrna.fa.txt](https://github.com/user-attachments/files/16530463/OG0000775.mrna.fa.txt)
[output.afa.txt](https://github.com/user-attachments/files/16530573/output.afa.txt)

Same as last time, I added ".txt" to the fasta extension so Github would accept them.

I really appreciate your help, thanks a lot! If there is still no problem on your end, I am also available for a Zoom call if needed. 

Best,
Marion

**Comment by JLSteenwyk** [comment]
Hi Marion,

I just wanted to let you know that I have not forgotten about this!

We are narrowing in on a remedy and should be cutting a new release soon. My sincere apologies for the delay!

best,

Jacob

**Comment by JLSteenwyk** [comment]
Hi Marion,

My apologies for this issue not being resolved promptly. A confluence of factors — travel, time off, etc. — got in the way.

Nonetheless, I am happy to share that the issue has been resolved as of PhyKIT, v1.20.0.

Based on your feedback, we have also updated the documentation and help message to more clearly specify that the untrimmed alignment should be used as input to PhyKIT using the `-p` argument. We apologize for the lack of clarity in the prior version of the documentation.

Thank you for using PhyKIT and ClipKIT. We hope to keep bringing you software and tooling that enable your research and welcome any recommendations or suggestions you may have for new functions or whatever the case may be.

Cheers,

Jacob
